### ISSUE TITLE
In Which Folder downloaded scripts are stored and how to execute them

### ISSUE THREAD

**Issue by HarshalShende** [jahwi/bget#1]

**Comment by jahwi** [comment]
Run `bget -query scl` to check the current script download directory. The default directory is %appdata%\Bget\scripts.
You can execute scripts by going into the aforementioned download directory, opening the  folder named after the package you just downloaded, and after checking the code, running the scripts you find inside.

**Comment by HarshalShende** [comment]
yeah its there, Thank you ..you have not mentioned this in documentation
